CREATE TABLE IF NOT EXISTS otps (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    used boolean DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
   );
CREATE INDEX IF NOT EXISTS idx_otps_username ON otps (username);